# Generated by Django 5.0.2 on 2024-02-24 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("socialMedia", "0005_alter_comment_id_alter_post_id_alter_socialmedia_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="icon",
        ),
    ]
